# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SocketChat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Socket.IO-Client-Swift', '~> 14.0.0'
	pod 'Alamofire', '~> 4.5'
	pod 'FMDB'
	
  # Pods for SocketChat

end
